config/routes.rb
require 'sidekiq/web'

Ipdb::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  devise_scope :user do
    get 'users/select_plan', to: 'users/registrations#select_plan', as: 'select_plan'
    get 'users/select_silver', to: 'users/registrations#select_silver', as: 'select_silver'
    post 'users/finish', to: 'users/registrations#finish', as: 'finish'
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "omniauth_callbacks"
  }

  mount Commontator::Engine => '/commontator'

  root "pages#home"
  get "dashboard" => "pages#dashboard"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  get "media" => "pages#media"
  get "terms" => "pages#terms"
  get "ppff" => "pages#ppff"
  get "faq" => "pages#faq"
  get "pricing" => "pages#pricing"

  resources :user, :path => "users" do
    get :autocomplete_user_username, :on => :collection
  end

  resources :podcasts do
    get :autocomplete_podcast_name, :on => :collection

    resources :people_podcasts, :path => :connections, only: [:new, :create]
    member do
      get :follow
      get :unfollow
      get :ppff
      put "like", to: "podcasts#upvote"
      post :count
    end

    resources :reviews, only: [:index, :new, :create, :update, :destroy]
  end

  resources :reviews, only: [:show] do
    resource :comment, only: [:create, :update, :destroy], controller: :review_comment
  end

  resources :people do
    get :autocomplete_person_name, :on => :collection
    post :search, :on => :collection
  end
  resources :companies do
    resources :companies_people, only: [:new, :create]
    resources :companies_podcasts, :path => :connections, only: [:new, :create]
  end

  resource :search, only: :show, controller: :search
  #profile
  get 'profile/overview',  to: 'profile#overview'
  get 'profile/podcasts',  to: 'profile#podcasts'
  get 'profile/companies', to: 'profile#companies'
  get 'profile/messages',  to: 'profile#messages'
  get    'profile/messages/incomings/:id', to: 'incomings#show', as: 'incoming'
  delete 'profile/messages/incomings/:id', to: 'incomings#destroy'
  delete 'incomings/delete_bunch', to: 'incomings#delete_bunch'
  get 'profile/messages/sent/:id', to: 'messages#show', as: 'sent'
  get 'profile/subscription', to: 'profile#subscription'

  resources :messages, only: :create

  post 'stripe/webhook', to: 'stripe#webhook'
  post 'subscription/upgrade', to: 'subscriptions#upgrade'
  post 'subscription/downgrade', to: 'subscriptions#downgrade'
  post 'subscription/create', to: 'subscriptions#create'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  belongs_to :podcast
  validates :subject, :body, :sender_id, :podcast_id, presence: true
  validate :ownership

  scope :desc, -> { order(created_at: :desc) }

  private

  def ownership
    podcasts_ids = PersonPodcast.where(person_id: sender.person_id, position: 'Host').pluck(:podcast_id)
    unless podcasts_ids.include?(podcast_id)
      errors[:base] << 'only podcast host can send message to followers'
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < UserAccessController

  def create
    @message = current_user.sent_messages.build(message_params)
    authorize! :create, @message
    respond_to do |format|
      if @message.save
        @message.podcast.followers.each do |follower|
          follower.incomings.create(message_id: @message.id)
        end
        format.html { redirect_to @message, notice: 'Message has been sent.' }
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @message = current_user.sent_messages.find(params[:id])
    authorize! :read, @message
    @unread_count = current_user.incoming_messages.count
    respond_to do |format|
      format.html { render 'show' }
      format.js   {}
    end
  end

  private

  def message_params
    params.require(:message).permit(:podcast_id, :subject, :body)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def time_date(date)
    return unless date
    if date.year > Time.now.year
      date.strftime('%d/%m/%y')
    else
      date.to_date == Time.now.to_date ? date.strftime('%l:%M %P') : date.strftime('%b %d')
    end
  end

  def strip_html_tags(text)
    if text
      sanitize(text, tags: ['br']).gsub('<br>', ' ')
    end
  end
end

app/views/messages/_incoming.html.erb
<%= content_tag(:li, class: "list-group-item message #{'unread' unless incoming.read}") do %>
<a href="<%= incoming_path(incoming) %>" class="link-to"></a>
  <div class="name-and-time">
    <div class="time pull-right">
      <small class="pull-right">
        <span><%= time_date(incoming.created_at) %></span>
        <i class="icon-time"></i>
      </small>
    </div>
    <div class="name Kg">
      <span><%= incoming.message.podcast.name %></span>
    </div>
  </div>
  <div>
    <div class="pull-left">
      <div style="display:inline-block;">
        <input type="checkbox" name="ids[]" value="<%= incoming.id %>">
      </div>
    </div>
    <div class="subject Kg">
      <%= strip_html_tags incoming.message.subject %>
    </div>
  </div>
  <div class="body Kg">
    <%= strip_html_tags incoming.message.body %>
  </div>
<% end %>

app/views/messages/_index_can_compose.html.erb
<div class="messages">
  <h1 class="page-header">Messages</h1>

  <div class="row">
    <div class="col-xs-12">
      <div class="top-btn-group">
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#compose">COMPOSE</button>
        <button type="button" id="delete" disabled="disabled" class="btn btn-default" aria-label="Delete" data-toggle="tooltip" data-placement="bottom" title="Delete">
          <span class="glyphicon glyphicon-trash"></span>
        </button>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active" role="presentation">
          <a href="#inbox" class="green-border" aria-controls="inbox" role="tab" data-toggle="tab">
            <i class="fa fa-inbox text-green"></i>
            From My Followings
          </a>
        </li>
        <li role="presentation">
          <a href="#published" class="purple-border" aria-controls="published" role="tab" data-toggle="tab">
            <i class="icon-comments text-purple"></i>
            Published
          </a>
        </li>
      </ul>

      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="inbox">
          <% if @incomings.blank? %>
            <div style="padding: 60px 0px;margin-left:auto;margin-right:auto;max-width:400px;">
              <h4>Your inbox tab is empty.</h4>
            </div>
          <% else %>
            <ul class="list-group messages-list">
              <%= render partial: 'messages/incoming', collection: @incomings %>
            </ul>
          <% end %>
        </div>
        <div role="tabpanel" class="tab-pane" id="published">
          <% if @published.blank? %>
            <div style="padding: 60px 0px;margin-left:auto;margin-right:auto;max-width:400px;">
              <h4>Your published tab is empty.</h4>
              <p>
                Use Compose button if you want send message to your followers.
              </p>
            </div>
          <% else %>
            <ul class="list-group messages-list">
              <%= render partial: 'messages/sent', collection: @published %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.modal compose message -->
<div class="modal" id="compose">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#353535;">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h5 class="modal-title" style="color:white;">Compose Message</h5>
      </div>
      <%= form_for @message, html: {class: 'form-horizontal', role: 'form'}, remote: true, format: :json do |f| %>
      <div class="modal-body">
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">Podcast</div>
              <%= f.collection_select :podcast_id, @podcasts, :id, :name, {}, {class: 'form-control', id: 'inputPodcast'} %>
            </div>
            <%= f.text_field :subject, class: 'form-control', id: 'inputSubject', placeholder: 'Subject', required: true %>
          </div>
          <div class="editor">
            <%= f.text_field :body, id: 'inputBody', type: 'hidden' %>
            <trix-editor input="inputBody"></trix-editor>
          </div>
      </div>
      <div class="modal-footer">
        <!--
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-warning pull-left">Save Draft</button>
        -->
        <div class="row">
          <div class="col-sm-offset-9 col-sm-3">
            <%= f.submit 'Send', class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/_index_cannot_compose.html.erb
<div class="messages">
  <h1 class="page-header">Messages</h1>

  <div class="row">
    <div class="col-xs-12">
      <div class="top-btn-group">
        <button type="button" id="delete" disabled="disabled" class="btn btn-default" aria-label="Delete" data-toggle="tooltip" data-placement="right" title="Delete">
          <span class="glyphicon glyphicon-trash"></span>
        </button>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active" role="presentation">
          <a href="#inbox" class="active" aria-controls="inbox" role="tab" data-toggle="tab">
            <i class="fa fa-inbox text-green"></i>
            From My Followings
          </a>
        </li>
      </ul>

      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="inbox">
          <% if @incomings.blank? %>
            <div style="padding: 60px 0px;margin-left:auto;margin-right:auto;max-width:400px;">
              <h4>Your inbox tab is empty.</h4>
            </div>
          <% else %>
            <ul class="list-group messages-list">
              <%= render partial: 'messages/incoming', collection: @incomings %>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/messages/_sent.html.erb
<li class="list-group-item message">
  <a href="<%= sent_path(sent) %>" class="link-to"></a>
  <div class="name-and-time">
    <div class="time pull-right">
      <small class="pull-right">
        <span><%= time_date(sent.created_at) %></span>
        <i class="icon-time"></i>
      </small>
    </div>
    <div class="name Kg">
      <span><%= sent.podcast.name %></span>
    </div>
  </div>
  <div>
    <div class="pull-left">
      <div style="display:inline-block;">
        <input type="checkbox">
      </div>
    </div>
    <div class="subject Kg">
      <%= strip_html_tags sent.subject %>
    </div>
  </div>
  <div class="body Kg">
    <%= strip_html_tags sent.body %>
  </div>
</li>

app/views/messages/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render 'profile/sidebar' %>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <div class="message__top-btn-group">
        <%= link_to profile_messages_path,
                    type: 'button',
                    class: 'btn btn-default',
                    title: 'Back',
                    data: {toggle: 'tooltip', placement: 'bottom'} do %>
          <i class="fa fa-long-arrow-left fa-lg"></i>
        <% end %>
        <% if @incoming %>
          <%= link_to incoming_path(@incoming),
                      method: :delete,
                      type: 'button',
                      class: 'btn btn-default',
                      title: 'Delete',
                      data: {toggle: 'tooltip', palcement: 'bottom'} do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        <% else %>
          <button type="button" disabled="disabled" class="btn btn-default" aria-label="Delete" data-toggle="tooltip" data-placement="bottom" title="Delete">
            <span class="glyphicon glyphicon-trash"></span>
          </button>
        <% end %>
      </div>
      <div class="message__head__subject">
        <h2 class="page-header"><%= @message.subject.capitalize %></h2>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <div class='message__head'>
            <%= link_to @message.podcast do %>
              <%= image_tag podcast_art_url(@message.podcast, :thumb), class: 'podcast-art--thumb' %>
            <% end %>
            <div class='message__head__from'>
              <%= link_to @message.podcast.name.truncate(100), @message.podcast, class: 'message__head__from__podcast-name' %>
              <%= link_to @message.sender.person, class: 'message__head__from__user-name' do %>
                <%=  "<#{@message.sender.person.name.truncate(100)}>" %>
              <% end %>
              <span class="message__head__from__unfollow-lnk">
                <% if current_user.following?(@message.podcast) %>
                  <%= link_to 'unfollow', unfollow_podcast_path(@message.podcast), id: 'unfollow' %>
                <% else %>
                  <%= link_to 'follow', follow_podcast_path(@message.podcast) %>
                <% end %>
              </span>
            </div>
            <span class="message__head__time pull-right">
              <%= time_date @message.created_at %>
            </span>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="message__body">
            <%= @message.body.html_safe %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>