config/routes.rb
require 'sidekiq/web'

Ipdb::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  devise_scope :user do
    get 'users/select_plan', to: 'users/registrations#select_plan', as: 'select_plan'
    get 'users/select_silver', to: 'users/registrations#select_silver', as: 'select_silver'
    post 'users/finish', to: 'users/registrations#finish', as: 'finish'
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "omniauth_callbacks"
  }

  mount Commontator::Engine => '/commontator'

  root "pages#home"
  get "dashboard" => "pages#dashboard"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  get "media" => "pages#media"
  get "terms" => "pages#terms"
  get "ppff" => "pages#ppff"
  get "faq" => "pages#faq"
  get "pricing" => "pages#pricing"

  resources :user, :path => "users" do
    get :autocomplete_user_username, :on => :collection
  end

  resources :podcasts do
    get :autocomplete_podcast_name, :on => :collection

    resources :people_podcasts, :path => :connections, only: [:new, :create]
    member do
      get :follow
      get :unfollow
      get :ppff
      put "like", to: "podcasts#upvote"
      post :count
    end

    resources :reviews, only: [:index, :new, :create, :update, :destroy]
  end

  resources :reviews, only: [:show] do
    resource :comment, only: [:create, :update, :destroy], controller: :review_comment
  end

  resources :people do
    get :autocomplete_person_name, :on => :collection
    post :search, :on => :collection
  end
  resources :companies do
    resources :companies_people, only: [:new, :create]
    resources :companies_podcasts, :path => :connections, only: [:new, :create]
  end

  resource :search, only: :show, controller: :search
  #profile
  get 'profile/overview',  to: 'profile#overview'
  get 'profile/podcasts',  to: 'profile#podcasts'
  get 'profile/companies', to: 'profile#companies'
  get 'profile/messages',  to: 'profile#messages'
  get    'profile/messages/incomings/:id', to: 'incomings#show', as: 'incoming'
  delete 'profile/messages/incomings/:id', to: 'incomings#destroy'
  delete 'incomings/delete_bunch', to: 'incomings#delete_bunch'
  get 'profile/messages/sent/:id', to: 'messages#show', as: 'sent'
  get 'profile/subscription', to: 'profile#subscription'

  resources :messages, only: :create

  post 'stripe/webhook', to: 'stripe#webhook'
  post 'subscription/upgrade', to: 'subscriptions#upgrade'
  post 'subscription/downgrade', to: 'subscriptions#downgrade'
  post 'subscription/create', to: 'subscriptions#create'
end

app/models/company.rb
class Company < ActiveRecord::Base
  include PrettyId
  has_many :companies_people, dependent: :destroy
  has_many :people, through: :companies_people
  has_many :companies_podcasts, dependent: :destroy
  has_many :podcasts, through: :companies_podcasts
  alias_attribute :owner_id, :user_id

  validates :name, presence: true, allow_blank: false

  has_attached_file :image, styles: {medium: '256x256', thumb: '128x128', small: '64x64'},
    default_url: ':company_placeholder'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  acts_as_commontable
  acts_as_votable
  letsrate_rateable

  scope :approved, -> { where(approved: true) }

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

  # ABILITY
  # Monkey patch can_rate? method for Letsrate gem.
  # Basic user (not payed subscriber) can't rate. As well as guest(handled by super)
  def can_rate?(user, dimension=nil)
    return false if user && user.basic?
    super
  end

  def address
    [city, state, country].reject(&:blank?).join(', ')
  end
end

app/controllers/companies_controller.rb
class CompaniesController < UserAccessController
  before_action :set_company, only: [:show, :edit, :update]
  authorize_resource

  def index
    @companies = company_scope.page(params[:page])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.companies_people << CompanyPerson.new(person: current_person, company: @company, owner: true, approved: true)
    respond_to do |format|
      if @company.save
        format.html { redirect_to({action: 'index'}, notice: 'Thank you for submiting your company. It is currently being proccesed. Please allow 1-2 weeks for your company to be verified.')}
      else
        flash.now[:alert] = 'Something went wrong. Try again or contact administrator.'
        format.html { render action: 'new' }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to(@company, notice: 'Company successfuly updated.') }
      else
        flash.now[:alert] = 'Something went wrong. Try again or contact administrator.'
        format.html { render action: 'edit' }
      end
    end
  end

  def show
    @company_person = @company.companies_people.build(person_id: current_user.person_id)
    @podcasts = Podcast.joins(:companies_podcasts).
      where('companies_podcasts.company_id = ? AND companies_podcasts.approved = ?', @company.id, true)
    @people = Person.joins(:companies_people)
      .where('companies_people.company_id = ? AND companies_people.approved = ?', @company.id, true)
      .includes(:user)
  end

  private

  def company_params
    params.require(:company).permit(:name, :city, :state, :country, :image, :url)
  end

  def company_scope
    Company.approved
  end

  def set_company
    @company ||= company_scope.friendly.find(params[:id])
  end
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image, 'Image(logo)' %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :country %>
    <%= f.select :country, [], {}, {class: 'form-control bfh-countries', data: {country: @company.country || 'US'}}%>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.select :state, [], {}, {class: 'form-control bfh-states', data: {country: 'company_country', state: @company.state}} %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url, 'Web site link' %>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/companies/_people.html.erb
<div class="people">
<% if @people.any? %>
  <table class="table">
    <thead>
      <td></td>
      <td>Name</td>
      <td>Score</td>
    </thead>
    <tbody>
    <% @people.each do |person| %>
    <tr>
      <td style="width:58px;">
        <%= link_to person do %>
          <%= image_tag person.user.profile_image, alt: person.name, class: 'avatar' %>
        <% end %>
      </td>
      <td>
        <%= link_to person.name, person %>
      </td>
      <td>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p class="lead">No people yet.</p>
<% end %>
</div>

app/views/companies/_podography.html.erb
<div class="podography">
  <% if @podcasts.any? %>
    <table class="table">
      <thead>
        <td></td>
        <td>Name</td>
        <td>Description</td>
        <td>Score</td>
      </thead>
      <tbody>
      <% @podcasts.each do |podcast| %>
      <tr>
        <td style="width:58px;">
          <%= link_to podcast do %>
            <%= image_tag podcast.image, alt: podcast.name, title: podcast.name, class: 'podcast-art' %>
          <% end %>
        </td>
        <td>
          <%= link_to podcast.name, podcast %>
        </td>
        <td>
          <%= truncate(podcast.description, length: 100) %>
        </td>
        <td>
          <%= number_with_delimiter((podcast.score * 100000).to_i) %>
        </td>
      </tr>
      </tbody>
      <% end %>
    </table>
  <% else %>
    <p class="lead">No podcasts yet.</p>
  <% end %>
</div>

app/views/companies/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10">
      <h1>Edit Company</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>Listing companies</h1>
    </div>
    <div class="col-md-6">
      <% if can? :create, Company %>
        <span class="help-block pull-right">Don't see your company listed? Get your company listed here today.</span>
        <br/><br />
        <%= link_to 'Add New Company', new_company_path, class: "btn btn-primary btn-lg pull-right" %>
      <% end %>
    </div>
  </div>
  <div class="row companies">
    <div class="col-sm-12">
      <%= paginate @companies %>
      <hr />
      <% if can? :show, Company %>
        <% @companies.each do |company| %>
        <li class="well col-md-2">
          <%= link_to company do %>
            <%= image_tag company.image, alt: company.name, class: 'company-logo' %>
          <% end %>
          <br />
          <div class="rating-box">
            <%= rating_for company %>
          </div>
          <h4><%= link_to company.name, company %></h4>
        </li>
        <% end %>
      <% else %>
        <% @companies.each do |company| %>
        <li class="well col-md-2">
          <%= image_tag 'upgrade_to_ipdb_silver.jpg', alt: company.name, class: 'company-logo' %>
          <br />
          <div class="rating-box">
          </div>
          <h4><%= company.name %></h4>
        </li>
        <% end %>
      <% end %>
      <%= paginate @companies %>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10">
      <h1>New Company</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <h3><%= link_to @company.name, @company.url %></h3>
      <%= image_tag @company.image, class: 'company-logo' %>
      <div class="company-rank"></div>
      <br />
      <% if can?(:create, @company_person) && @company_person %>
        <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#addProfile">
          Connect Profile
        </button>
      <% end %>
      <% if can?(:create, CompanyPodcast) %>
        <%= link_to 'Connect Podcast', new_company_company_podcast_path(@company), class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
    <div class="col-sm-9">
      <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="#podography" role="tab" data-toggle="tab">Podography</a></li>
        <li><a href="#people" role="tab" data-toggle="tab">People</a></li>
        <li><a href="#reviews" role="tab" data-toggle="tab">Reviews</a></li>
      </ul>
      <br />
      <div class="tab-content">
        <div class="tab-pane active" role="tabpanel" id="podography">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= render 'podography' %>
            </div>
          </div>
        </div>
        <div class="tab-pane" role="tabpanel" id="people">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= render 'people' %>
            </div>
          </div>
        </div>
        <div class="tab-pane" role="tabpanel" id="reviews">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= commontator_thread(@company) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br />
  <%= link_to :back, companies_path %>
</div>

<% if can?(:create, @company_person) %>
  <div class="modal fade" id="addProfile" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <%= form_for @company_person, url: company_companies_people_path(@company) do |f| %>
      <div class="modal-content">
        <div class="modal-header" style="border: 0px;">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body" style="font-size: 1.1em;">
          <br />
          <span>Do you want connect your profile to <strong><%= @company.name %></strong>?</span>
          <br />
        </div>
        <div class="modal-footer" style="border: 0px;">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Yes, I want", class: 'btn btn-primary' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
<% end %>