config/routes.rb
require 'sidekiq/web'

Ipdb::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  post '/rate' => 'rater#create', :as => 'rate'

  devise_scope :user do
    get 'users/select_plan', to: 'users/registrations#select_plan', as: 'select_plan'
    get 'users/select_silver', to: 'users/registrations#select_silver', as: 'select_silver'
    post 'users/finish', to: 'users/registrations#finish', as: 'finish'
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "omniauth_callbacks"
  }

  mount Commontator::Engine => '/commontator'

  root "pages#home"
  get "dashboard" => "pages#dashboard"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  get "media" => "pages#media"
  get "terms" => "pages#terms"
  get "ppff" => "pages#ppff"
  get "faq" => "pages#faq"
  get "pricing" => "pages#pricing"

  resources :user, :path => "users" do
    get :autocomplete_user_username, :on => :collection
  end

  resources :podcasts do
    get :autocomplete_podcast_name, :on => :collection

    resources :people_podcasts, :path => :connections, only: [:new, :create]
    member do
      get :follow
      get :unfollow
      get :ppff
      put "like", to: "podcasts#upvote"
      post :count
    end

    resources :reviews, only: [:index, :new, :create, :update, :destroy]
  end

  resources :reviews, only: [:show] do
    resource :comment, only: [:create, :update, :destroy], controller: :review_comment
  end

  resources :people do
    get :autocomplete_person_name, :on => :collection
    post :search, :on => :collection
  end
  resources :companies do
    resources :companies_people, only: [:new, :create]
    resources :companies_podcasts, :path => :connections, only: [:new, :create]
  end

  resource :search, only: :show, controller: :search
  #profile
  get 'profile/overview',  to: 'profile#overview'
  get 'profile/podcasts',  to: 'profile#podcasts'
  get 'profile/companies', to: 'profile#companies'
  get 'profile/messages',  to: 'profile#messages'
  get    'profile/messages/incomings/:id', to: 'incomings#show', as: 'incoming'
  delete 'profile/messages/incomings/:id', to: 'incomings#destroy'
  delete 'incomings/delete_bunch', to: 'incomings#delete_bunch'
  get 'profile/messages/sent/:id', to: 'messages#show', as: 'sent'
  get 'profile/subscription', to: 'profile#subscription'

  resources :messages, only: :create

  post 'stripe/webhook', to: 'stripe#webhook'
  post 'subscription/upgrade', to: 'subscriptions#upgrade'
  post 'subscription/downgrade', to: 'subscriptions#downgrade'
  post 'subscription/create', to: 'subscriptions#create'
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :plan
  belongs_to :user

  validates :user, :plan, :start_date, :end_date, presence: true

  def sync
    customer = retrieve_stripe_customer
    subscription = retrieve_subscription(customer)
    update_from_event(subscription)
    update_user
  end

  def upgrade
    customer = retrieve_stripe_customer
    subscription = retrieve_subscription(customer)
    return if subscription.plan.id == Plan.silver.stripe_id

    if user.allowed_to_silver_trial?
      response = customer.update_subscription(plan: Plan.silver.stripe_id)
    else
      response = customer.update_subscription(plan: Plan.silver.stripe_id, trial_end: 'now')
    end
    update_from_event(response)
    update_user
  end

  def downgrade
    customer = retrieve_stripe_customer
    subscription = retrieve_subscription(customer)
    return if subscription.plan.id == Plan.basic.stripe_id

    response = customer.update_subscription(plan: Plan.basic.stripe_id)
    update_from_event(response)
    update_user
  end

  def create(card_token)
    return if user.customer_id
    user.membership = Plan.silver.name
    user.card_token = card_token
    user.create_stripe_customer
    user.save!
    sync
  end

  def retrieve_stripe_customer
    Stripe::Customer.retrieve(user.customer_id)
  end

  def retrieve_subscription(customer)
    customer.subscriptions.retrieve(customer.subscriptions.data[0].id)
  end

  def update_from_event(subscription)
    self.status      = subscription.status
    self.start_date  = to_date_time(subscription.current_period_start)
    self.end_date    = to_date_time(subscription.current_period_end)
    self.trial_start = to_date_time(subscription.trial_start)
    self.trial_end   = to_date_time(subscription.trial_end)
    self.plan        = Plan.find_by(stripe_id: subscription.plan.id)
    self.save!
  end

  def update_user
    user.active_until = end_date
    user.membership = plan.name
    user.save!
  end

  def to_date_time(digits)
    Time.at(digits)
  rescue TypeError
    nil
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < UserAccessController
  rescue_from Stripe::StripeError, with: :stripe_error

  def upgrade
    respond_to do |format|
      if Subscription.new(user: current_user).upgrade
        format.html { redirect_to profile_subscription_path, notice: "Your plan has been upgraded to #{Plan.silver.name}" }
        format.json { head :no_content }
      else
        format.html { redirect_to profile_subscription_path, notice: "Your plan can't be upgraded to #{Plan.silver.name}" }
        format.json { head :unprocessable_entity }
      end
    end
  end

  def downgrade
    respond_to do |format|
      if Subscription.new(user: current_user).downgrade
        format.html { redirect_to profile_subscription_path, notice: "Your plan has been downgraded to #{Plan.basic.name}" }
        format.json { head :no_content }
      else
        format.html { redirect_to profile_subscription_path, notice: "Your plan can't be downgraded to #{Plan.basic.name}" }
        format.json { head :unprocessable_entity }
      end
    end
  end

  def create
    card_token = params[:user][:card_token]
    respond_to do |format|
      if Subscription.new(user: current_user).create(card_token)
        format.json { head :no_content }
      else
        format.json { head :unprocessable_entity }
      end
    end
  end

  private

  def stripe_error(e)
    respond_to do |format|
      format.html { redirect_to profile_subscription_path, notice: e.message }
      format.json { render json: e.message, status: :unprocessable_entity }
    end
  end
end

app/views/subscriptions/_basic.html.erb
<div class="row">
  <div class="col-sm-8">
    <table class="table subscription-table">
      <colgroup>
        <col span="1" style="width: 50%;">
        <col span="1" style="width: 30%;">
        <col span="1" style="width: 20%;">
      </colgroup>
      <thead>
        <tr>
          <th><h3>Plan details</h3></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            Current plan
          </td>
          <td>
            <span>Basic</span>
          </td>
          <td>
            <button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#upgrade-plan-modal">Upgrade to silver</button>
          </td>
        </tr>
        <tr>
          <td>
            Status
          </td>
          <td>
            <%= @subscription.status.capitalize %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Cost
          </td>
          <td>
            $0.00 per month
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Subscription started
          </td>
          <td>
            <%= l @subscription.start_date, format: :short %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Next billing date
          </td>
          <td>
            <%= l @subscription.end_date, format: :short %>
          </td>
          <td></td>
        </tr>
      </tbody>
      <tfoot>
        <tr><td></td><td></td><td></td></tr>
      </tfoot>
    </table>
  </div>
</div>
<!-- /.modal upgrade with billing -->
<div class="modal" id="upgrade-plan-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h5 class="modal-title">Upgrade to silver plan</h5>
      </div>
      <%= form_tag subscription_upgrade_path, id: 'upgrade-plan', remote: true, data: { type: 'json' } do %>
      <div class="modal-body">
        <p>You will be charged $13 for 30 days.</p>
        <div class="checkbox">
          <label>
            <%= check_box_tag :agree, :yes, false, {required: true} %>
            I want upgrade my plan to silver.
          </label>
        </div>
      </div>
      <div class="modal-footer">
        <!--
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-warning pull-left">Save Draft</button>
        -->
        <div class="row">
          <div class="col-sm-offset-9 col-sm-3">
            <%= submit_tag 'Upgrade', class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/subscriptions/_not_subscriber.html.erb
<div class="row">
  <div class="col-sm-8">
    <table class="table subscription-table">
      <colgroup>
        <col span="1" style="width: 50%;">
        <col span="1" style="width: 30%;">
        <col span="1" style="width: 20%;">
      </colgroup>
      <thead>
        <tr>
          <th><h3>Plan details</h3></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            Current plan
          </td>
          <td>
            <span>Basic</span>
          </td>
          <td>
            <button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#upgrade-billing">Upgrade to silver (14-day trial)</button>
          </td>
        </tr>
        <tr>
          <td>
            Status
          </td>
          <td>
            Active
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Cost
          </td>
          <td>
            $0.00 per month
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Subscription started
          </td>
          <td>
            <%= l current_user.created_at, format: :short %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Next billing date
          </td>
          <td>
          </td>
          <td></td>
        </tr>
      </tbody>
      <tfoot>
        <tr><td></td><td></td><td></td></tr>
      </tfoot>
    </table>
  </div>
</div>
<!-- /.modal upgrade with billing -->
<div class="modal" id="upgrade-billing">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h5 class="modal-title">Upgrade to silver plan</h5>
      </div>
      <%= form_tag subscription_create_path, id: 'upgrade-silver-billing', remote: true, data: { type: 'json' } do %>
      <div class="modal-body">
        <%= render partial: 'devise/registrations/billing' %>
      </div>
      <div class="modal-footer">
        <!--
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-warning pull-left">Save Draft</button>
        -->
        <div class="row">
          <div class="col-sm-offset-9 col-sm-3">
            <%= submit_tag 'Upgrade', class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/subscriptions/_silver.html.erb
<div class="row">
  <div class="col-sm-8">
    <table class="table subscription-table">
      <colgroup>
        <col span="1" style="width: 50%;">
        <col span="1" style="width: 30%;">
        <col span="1" style="width: 20%;">
      </colgroup>
      <thead>
        <tr>
          <th><h3>Plan details</h3></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            Current plan
          </td>
          <td>
            <span>Silver</span>
          </td>
          <td>
            <button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#downgrade-plan-modal">Downgrade to basic</button>
          </td>
        </tr>
        <tr>
          <td>
            Status
          </td>
          <td>
            <%= @subscription.status.capitalize %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Cost
          </td>
          <td>
            $13.00 per month
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Subscription started
          </td>
          <td>
            <%= l @subscription.start_date, format: :short %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            Next billing date
          </td>
          <td>
            <%= l @subscription.end_date, format: :short %>
          </td>
          <td></td>
        </tr>
      </tbody>
      <tfoot>
        <tr><td></td><td></td><td></td></tr>
      </tfoot>
    </table>
  </div>
</div>
<!-- /.modal upgrade with billing -->
<div class="modal" id="downgrade-plan-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h5 class="modal-title">Downgrade to basic plan</h5>
      </div>
      <%= form_tag subscription_downgrade_path, id: 'downgrade-plan', remote: true, data: { type: 'json' } do %>
      <div class="modal-body">
        <div class="checkbox">
          <label>
            <%= check_box_tag :agree, :yes, false, {required: true} %>
            I want downgrade my plan to basic.
          </label>
        </div>
      </div>
      <div class="modal-footer">
        <!--
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-warning pull-left">Save Draft</button>
        -->
        <div class="row">
          <div class="col-sm-offset-9 col-sm-3">
            <%= submit_tag 'Downgrade', class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>